# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.8"
services: 
    sql-server-db: 
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment: 
            SA_PASSWORD: "sql@2020"
            ACCEPT_EULA: "Y"
    # classroom-api:
    #     container_name: classroom-api
    #     image: classroom
    #     build:
    #         context: .
    #         dockerfile: ClassRoom/ClassRoom/Dockerfile
    #     ports:
    #         - 80
    #     restart: always
    #     depends_on: 
    #         - sql-server-db